project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "case-studies/*.qmd"

website:
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: prework.qmd
        text: Prework
      - href: setup-guide.qmd
        text: Setup Guide
      - href: resources.qmd
        text: Resources
      - href: q-and-a.qmd
        text: FAQs
      - text: Case Studies 
        menu:
          - text: Case Study 01 
            url:  case-studies/case-studies-01.qmd
          - text: Case Study 02 
            url:  case-studies/case-studies-02.qmd
          - text: Case Study 03 
            url:  case-studies/case-studies-03.qmd
          - text: Case Study 04 
            url:  case-studies/case-studies-04.qmd
          
    right:
      - icon: globe
        href: https://omicscenter.github.io/
      - icon: github
        href: https://github.com/omicscenter
      - icon: facebook
        href: https://www.facebook.com/omicscenter
      - icon: linkedin
        href: https://www.linkedin.com/company/chiral-bangladesh/
    page-navigation: true
  page-footer:
    left: "&copy; Copyright 2022, Md. Jubayer Hossain"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
format:
  html:
    theme: [journal, theme.scss]
    css: styles.css
    toc: true
    code-overflow: scroll
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y
editor: source 

